### ISSUE TITLE
Result is not accurate for a couple of cases 

### ISSUE THREAD

**Issue by whiz-Tuhin** [j2kun/guess-the-polynomial#1]
I had done a javascript implementation of the [article](https://jeremykun.com/2014/11/18/learning-a-single-variable-polynomial-or-the-power-of-adaptive-queries/) related to this repo, and I was testing it for a couple of polynomials.

I found out that when I put the following query, it gives only 2 terms of the polynomial that I had guessed

``` bash
 What is the value of P(1)? 
 11

 What is the value of P(12)?
 10417

 Your polynomial is: 

	  1 + 4 x^1 
```

Whereas, the polynomial that I had guessed was 

` 1 + 4 x^1 + 6 x^3 `

This was mainly because of the check (y % N != 0) in the loop where the coefficients are generated, as the loop terminates before generating the coefficient of `x^3`.

A similar issue when I plug in the following queries

```
What is the value of P(1)?
8

What is the value of P(9)?
408

Your polynomial is: 

	  3 
```
Whereas the polynomial that I had guessed was

`5 x^2 + 3`

Hence, as per my conclusion the condition of non-negetive integral coefficients should be changed to strictly positive integral coefficients, otherwise it works sporadically. 

Please correct me if I am wrong

**Comment by j2kun** [comment]
Ah, the issue is that the while loop condition should be `y > 0`. Since `y` represents the number `f(N)` written in base `N`, of course some of the digits of that representation can be zero. A simple example that breaks with the current code is `f(x) = x`, which it would report as the zero polynomial.

I've updated the code to match, and I think this problem was me just being sloppy and misreading my own old blog post. I'm sorry if it caused you to waste a lot of your time.

Thanks!
